name: weather
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  dio: ^5.4.3+1
  equatable: ^2.0.5
  bloc_concurrency: ^0.2.5
  syncfusion_flutter_sliders: ^26.1.35
  csv: ^6.0.0
  auto_size_text: ^3.0.0
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.3
  logger: ^2.3.0
  cached_network_image: ^3.3.1
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/countries.csv
